name: Testing

on:
    pull_request:
        types: [opened, synchronize, reopened]

permissions:
    pull-requests: write

jobs:
    run-simple-mediatR-tests:
        uses: ./.github/workflows/base.yaml
        with:
            test_project_path: 'tests/SimpleMediatRTests'
            comment_tag: 'test-results-simplemediatR'
            test_project_name: 'SimpleMediatRTests'